import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import fs from "node:fs";
import path from "node:path";

import { Header } from "@/components/Header";
import { Hero } from "@/components/Hero";
import { About } from "@/components/About";
import { WorkExperience } from "@/components/WorkExperience";
import { Skills } from "@/components/Skills";
import { Projects } from "@/components/Projects";
import { ContactMe } from "@/components/ContactMe";
import { Footer } from "@/components/Footer";

type Props = {
  skills: Skill[];
  pageInfo: PageInfo;
  experiences: Experience[];
  projects: Project[];
  socials: Social[];
};

const Home: NextPage<Props> = ({ pageInfo, skills, experiences, projects, socials }) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80 z-0">
      <Head>
        <title>{pageInfo.name}&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />

      <section id="hero" className="snap-start">
        <Hero pageInfo={pageInfo} />
      </section>

      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>

      <section id="experience" className="snap-center">
        <WorkExperience experiences={experiences} />
      </section>

      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>

      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>

      <section id="contact" className="snap-start">
        <ContactMe pageInfo={pageInfo} />
      </section>

      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const contentJsonPath = path.join(process.cwd(), "contents.json");
  const data = JSON.parse(fs.readFileSync(contentJsonPath, "utf8"));
  const pageInfo: PageInfo = data["pageInfo"];
  const skills: Skill[] = data["skills"];
  const experiences: Experience[] = data["experiences"];
  const projects: Project[] = data["projects"];
  const socials: Social[] = data["socials"];

  return {
    props: {
      skills,
      pageInfo,
      experiences,
      projects,
      socials,
    },
  };
};

export default Home;
